name: "Slack Failure Notifications"
description: Create slack notification for workflow failures
inputs:
  SLACK_API_TOKEN:
    description: Slack Auth
    required: true
  SLACK_WEBHOOK:
    description: Dev slack channel
    required: false
  SLACK_WEBHOOK_INFRA:
    description: Infra slack channel
    required: false
runs:
  using: composite
  steps:
    - name: Check secrets presence
      id: is-infra
      shell: bash
      run: |
        if [ "${{ inputs.SLACK_WEBHOOK }}" == "" ]; then
          echo ::set-output name=dev::false
        else
          echo ::set-output name=dev::true
        fi
        if [ "${{ inputs.SLACK_WEBHOOK_INFRA }}" == "" ]; then
          echo ::set-output name=infra::false
        else
          echo ::set-output name=infra::true
        fi
    - name: Debug Dev
      run: echo "Is dev ${{ steps.is-infra.outputs.dev }}"
      shell: bash
    - name: Debug Infra
      run: echo "Is infra ${{ steps.is-infra.outputs.infra }}"
      shell: bash
    - name: Get Actor
      shell: bash
      run: |
        echo "Get Actor for slack"
        if [ ${{ github.event.head_commit.author.name }} ]; then
          gh_user=${{ github.event.head_commit.author.name}}
        elif [ ${{ github.actor }} ]; then
          gh_user=${{ github.actor }}
        else
          gh_user=unknown
        fi
        echo $gh_user
        echo "gh_user=$gh_user" >> $GITHUB_ENV
    - name: Find Slack user
      if: ( github.ref_name == 'master' || github.ref_name == 'main' ) && steps.is-infra.outputs.dev == 'true'
      id: find-slack-user
      uses: circle9r/find-slack-user-action@v1.1.0
      with:
        slack-token: ${{ inputs.SLACK_API_TOKEN }}
        username: ${{ env.gh_user }}
    - name: Slack any failure
      uses: 8398a7/action-slack@v3
      if: ( github.ref_name == 'master' || github.ref_name == 'main' ) && steps.is-infra.outputs.dev == 'true'
      with:
        mention: '${{ steps.find-slack-user.outputs.member-id }}'
        if_mention: failure
        status: ${{ job.status }}
        fields: repo,author,commit,action,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK }}
    - name: Slack any failure to infra
      uses: 8398a7/action-slack@v3
      if: ( github.ref_name == 'master' || github.ref_name == 'main' ) && steps.is-infra.outputs.infra == 'true'
      with:
        mention: 'subteam^S02CZJ9RV6Y'
        if_mention: failure
        status: ${{ job.status }}
        fields: repo,author,commit,action,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_INFRA }}
